### ISSUE TITLE
smoke tests for travis

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/docker-existdb#24]
We can do simple smoke tests, 
by making each script line fail or succeed via exit codes

e.g.  At the moment the script line only shows
 - docker logs exist

revised smoke test - eXist should start
 - docker logs exist | grep 'Server has started'

**Comment by duncdrum** [comment]
that is a great idea. We could set up a matrix that runs with the default build-args`docker build .`  To check if Dashboard is reachable, and to check for more lines from the logs that we know should be there, e.g. EXIST_DATA, does the Version in the logs match the version we tried to build, etc 

One thing I liked about the old test was having the full exist.log, but using proper tests is much better

**Comment by duncdrum** [comment]
i'd say we're  past the point of simple smoke tests
