### ISSUE TITLE
Dockerfile build-args outline

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/docker-existdb#25]
Here is a proposal of what build-args should be provided in the Dockerfile

@ARG VERSION  - can be stable or RC e.g. '4.3.1'
                                - this a requirement of hooks/build, see notes below
@ARG BRANCH  - branch can be a
                 - branch name e.g release,develop, name-of-branch
                 - tagged commit e.g.  eXist-4.3.1
                 - any commit hash ( short or long )
                 e.g 3b19579, 3b195797a2c2f35913891412859b06d94f189229
@ARG BUILD_DATE
@ARG VCS_REF
@ARG CACHE_MEM
@ARG MAX_BROKER

NOTES: 
VERSION, BUILD_DATE, VCS_REF build-args are created via a dockerhub build hook in `hooks/build`
CACHE_MEM, MAX_BROKER  build args are available, if you want to override the defaults

Build process - build-args provided via `docker build` are optional. 
1.  if build-arg VERSION is empty, then version is ignored
2.  if build-arg BRANCH is empty then defaults to develop

**Comment by duncdrum** [comment]
I think this can be closed, no?
