### ISSUE TITLE
functional tests for travis

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/docker-existdb#27]
The functional tests would be on a running container.
The tests would aim to show if the changes we have made to a normal eXist install,
( to suite docker) are working properly.

changes to config files
 - copy a config file to host  
  => diff check that file in host is same as in container volume
- copy different config file(s) into container
   => diff check that file in container volume is same as copied file
  =>  stop and start container then check if changed startup option has been applied

changes to logging  
   execute commands in with start.jar client
 -  util:log() | grep => check stdout
 
more ..

**Comment by duncdrum** [comment]
I would suggest adding the following functional tests:
*   make sure that healthcheck passes (takes 30 seconds to report healthy) this means that exist is acting normally from within the JVM
*   make sure that dashboard is accessible (based on experience healthcheck is not enough for this)
*   Ideally we would check that no `ERROR` messages appear in the log after startup, but that test would currently fail.

**Comment by duncdrum** [comment]
Since exist 4.3.0 we don't have an error free start log, a test was part of my last commits. The remaining tests are already in and running on travis. Let's close and open a new issue if we need more or different tests.
