### ISSUE TITLE
take care of log4j2 customization during build time

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/docker-existdb#3]
same as duncdrum/exist-docker#5
having exist.log in stdout by default is pretty useful, we should just turn that on for all docker images. 
Right now we still risk having the log4j.xml get out of sync with upstream, by tweaking aureas we don't have to worry about that anymore.

**Comment by duncdrum** [comment]
aureas is out, but i d still prefer to have a way to dynamically modify conf files at build time.

**Comment by adamretter** [comment]
Why is Aureas out?

**Comment by duncdrum** [comment]
i don't think anything is calling it right now, we could use Aureas but would need to integrate it into the docker file, during the first build stage
