### ISSUE TITLE
running tests locally

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/docker-existdb#35]
#30 @adamretter 
> Also, perhaps it is better to extract the shell scripts from .travis.yml into a separate shell script. With a separate shell script, we can then also run the tests locally, and we can easily check and validate any syntax errors.

As it stands now,  the script blocks run sequentially,.
Each travis script block should either succeed or fail,  
When the script block fails, the travis build will fail
What I think I could do is
 - extract each script block as a  test-fixture (a stand alone bash script)
- create tests dir *t* ,  write tap tests, that check the output of the scripts err code and data

This way we could test locally (and in travis ),  by calling prove and getting a nice tap report.
A setup and tear down stage could be done via simple Makefile
```
test:
   docker-compose up d
   prove
   docker-compose down
```

**Comment by adamretter** [comment]
I wasn't asking for anything that complex :-) I still wanted the tests to run sequentially

**Comment by duncdrum** [comment]
while i m not opposed to the idea of using tap, my main concern is with improving parallel execution of our tests-suite on travis first. As it stands even the three smoke tests could be run in parallel, especially functional test should take advantage of paralleliml.  i ll have to think a bit more about how to best run tests locally,  but won't get around to it in the next two weeks.
