### ISSUE TITLE
:release and :latest have different EXIST_HOME env

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/docker-existdb#37]
release has `exist`
latest has `eXist` 

no clue how this happened, but we should harmonize. As it stands the same docker commands should work on both channels, they do not. Furthermore, once 5.0.0 is the new stable the paths would change anyways. So better to make the jump now for :latest imv, which would keep :release stable.   

Still I cannot guarantee that this will have 0 fallout for users, so apologies in advance.

**Comment by grantmacken** [comment]
LGTM  
I think the only place it should impact existing users 
 - when using the docker cp command with the previous path, while changing config files
- not updating their own .env file to reflect the new path when invoking docker compose
