### ISSUE TITLE
[housekeeping] remove build.sh

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/docker-existdb#38]
we're 99% there but building will fail when calls to build.sh are removed from the dockerfile.

**Comment by grantmacken** [comment]
> l will fail  when calls to build.sh are removed from the dockerfile.

So it should, because 
```
&& git clone --progress https://github.com/exist-db/exist.git \
&& cd $EXIST_MAX \
 ...
&& ./build.sh 
```
The called 'build.sh'  is the build.sh in the exist repo, 
not the 'build.sh' that remains in this repo.
As an aside the now redundant build.sh in this repo also called other 'build.sh' .

**Comment by duncdrum** [comment]
~~that was my thinking as well, but when i removed that call the build fails because of a later call to `rm -r EXIST_MAX` … some more fiddling is required~~ 

Oh my bad, i misunderstood.
