### ISSUE TITLE
Further configuration tweaks to conf.xml

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/docker-existdb#41]
The following line is giving me pause:
```xml
<watchdog output-size-limit="1000000" query-timeout="-1"/>
```

-   `query-timeout` while convenient, it means that orchestrators will probably keep a dead node around potentially indefinitely. I think in a container context this should have high positive value. 

Similarly, 
```xml
<recovery enabled="yes"  group-commit="no"   journal-dir="webapp/WEB-INF/data"
                  size="100M" sync-on-commit="no"  force-restart="no"  consistency-check="yes"/>
```

-   `sync-on-commit` My intuition (need to do some testing on this) is that sync-on-commit might actually speed up things in containerland, but I'm not sure how it would play out in different orchestration scenarios, what if a worker node never reaches the threshold? 

-   Enabling `force-restart` on the other hand might make sense, since new instances are created and killed much more frequently compared to traditional server contexts.

**Comment by adamretter** [comment]
Regards `query-timeout="-1"` I think we need to be clear what it actually means.

If will only abort a query that is in a healthy and running state, there are other reasons why a query may lock up, and in those instances `query-timeout` won't have any effect.

Actually `query-timeout` is rather dangerous as you can end up with unexpected inconsistencies if a query running an XQuery Update or XUpdate is aborted. The database itself won't be corrupted, but only some of the changes will have been applied, which means that your data may not be consistent.

Also if a database has locked up, you should not terminate it and try and continue. That will likely just result in a corrupted database.

Regards `sync-on-commit` I think its description is misleading. The sync happens asynchronously to the commit. So there is no guarantee of anything.

Regards `force-restart`... it should never be the default!

**Comment by duncdrum** [comment]
> If will only abort a query that is in a healthy and running state

that settles `query-timeout` then, let's keep it as is. 
as for the others thats why I was looking for feedback thanks @adamretter 

let's keep them as well.
