### ISSUE TITLE
build.sh redundant code

### ISSUE THREAD

**Issue by grantmacken** [eXist-db/docker-existdb#8]
Took a quick look at build.sh
I think this could do with a bit of a clean up.
It is now used inside docker,  so stuff like
```
# Either get or update from GitHub eXist-db
```
is redundant.
Most likely, build.sh could be removed all together, 
with everything going into the build target.

**Comment by adamretter** [comment]
I will have to leave @duncdrum to comment on this. As I am still not quite clear how the build process works now

**Comment by duncdrum** [comment]
hi welcome @grantmacken see #5, build.sh does a number of things right now, and is already used in one of the build stages. The main thing being modification of configuration files (i think there might be more modifications down the line we might want to do).
The other stuff such as tagging the image, etc should go into `hooks/build`, which removes a dependency for folks cloning the repo.

And yes more cleanup is always welcome, the more we can move into the dockerfile the better

**Comment by grantmacken** [comment]
#20  build.sh process logic now in Dockefile
